### ISSUE TITLE
Exploring DB password expiration options

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/cor-cm#38]

**Comment by kbowaterskelly** [comment]
The db passwords for the following were set to never expire. Beth has requested that I document all of the DB accounts in confluence. I'll confirm with her if these are the only relevant ones. (They aren't.)



'openemory'@'wlibqas001.library.emory.edu'

'pidman'@'wlibqas001.library.emory.edu'

'keep'@'vmch-webprd003.cc.emory.edu'

'keep'@'10.231.35.123'

**Comment by kbowaterskelly** [comment]
Here's a list of some of the DBs that may be relevant to us. I believe some of these can be ruled out, however I don't have enough information to say so definitively about many of them. That said, we can ask for any/all of our accounts to be set not to expire, since we are not subject to HIPAA or other compliance that forbids that.

Dev:

 

Canvas_Data

Canvas_Imports

Carlos_Dev

Digitizedbooks_Dev

Eaudition

Eulindexer_Dev

Filetool

Keep_Dev

Online_Investigators_Guide

Online_Investigators_Guide_QA

Openemory_Dev

Paa_Dev

Paa_QA

Phpsession_Dev

Pidman_Dev

Research_Template_Library_Dev

Reservations

 

 

QA:

 

Filetool

Phpsession_QA

Research_Template_Library_QA

 

 

Prod:

 

Canvas_Data

Canvas_Imports

Canvas_Imports_1

Digitizedbooks_Prod

Eaudition

Emorylib_Prod

Eulindexer_Prod

Filetool

Keep_Prod

Online_Investigators_Guide

Openemory_Prod

Paa_Prod

Phpsession_Prod

Pidman_Prod

Research_Template_Library_Prod
