### ISSUE TITLE
Investigate SSL cert automation

### ISSUE THREAD

**Issue by rotated8** [emory-libraries/cor-cm#40]
- [x] Contact Alan White to see if we can use the automation tools provided by InCommon.
- [x] Explore alternatives, e.g. LetsEncrypt, evaluate time/cost

**Comment by kbowaterskelly** [comment]
I think this will be a spike ticket. We should allocate time to it according to what the other enhancement sprint time requirements for my tickets are.

**Comment by kbowaterskelly** [comment]
We're having an account created to use InCommon ACME automation. If this is suitable for our purposes, it will handle the majority of the certificates, otherwise Let's Encrypt can be employed. AWS certs are the bulk of the remainder and have an easy method to automate, although I believe this will end up costing some money.

**Comment by kbowaterskelly** [comment]
I'm still working on delivering MVP of certbot/ACME deployment, but that seems more like a stretch goal than anything. The provided solutions should work for us.
